name: CI Mentoria

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Instalando as dependências
        run: npm install

      - name: Iniciar o servidor de mocks
        run: npm run mock-server

      - name: Iniciar o servidor de aplicacao
        run: npm run server

      - name: Executar os testes
        run: npx cypress run
